
import React, { useState } from 'react';
import { Atom } from '../types';
import { ATOM_COLORS } from '../constants';

interface PublisherProps {
  atoms: Atom[];
}

const Publisher: React.FC<PublisherProps> = ({ atoms }) => {
  const [selectedAtomId, setSelectedAtomId] = useState(atoms[0]?.id);
  const atom = atoms.find(a => a.id === selectedAtomId);

  const generateMarkdown = (target: Atom) => {
    return `---
title: "${target.name}"
description: "${target.content.summary || ''}"
tags:
  - ${target.type.toLowerCase()}
  - ${target.status.toLowerCase()}
  - criticality_${target.criticality.toLowerCase()}
---

# ${target.id}: ${target.name}

<div class="atom-card" data-type="${target.type}">
  <div class="atom-card-header">
    <span class="atom-card-id">${target.id}</span>
    <span class="atom-type-badge ${target.type.toLowerCase()}">${target.type}</span>
  </div>
</div>

## Description
${target.content.summary || 'No description provided.'}

${target.content.steps ? `## Steps
${target.content.steps.map((s, i) => `${i + 1}. ${s}`).join('\n')}` : ''}

${target.content.exceptions ? `## Exceptions
| Condition | Action |
|-----------|--------|
${target.content.exceptions.map(e => `| ${e.condition} | ${e.action} |`).join('\n')}` : ''}

## Relationships
${target.edges.map(e => `- [${e.targetId}](#) (${e.type})`).join('\n')}
`;
  };

  return (
    <div className="flex flex-col h-full bg-slate-950">
      <div className="p-8 border-b border-slate-800 bg-slate-900/40 flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold text-white mb-1 tracking-tight">Publisher Portal</h2>
          <p className="text-slate-400 text-sm">Preview MkDocs-compatible output generated by the build engine.</p>
        </div>
        <button className="bg-blue-600 hover:bg-blue-500 text-white px-6 py-2.5 rounded-xl font-black text-[10px] uppercase tracking-widest shadow-lg shadow-blue-900/30 transition-all flex items-center gap-2">
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12" />
          </svg>
          Trigger Global Build
        </button>
      </div>

      <div className="flex-1 flex overflow-hidden">
        {/* Navigation Sidebar */}
        <div className="w-64 border-r border-slate-800 bg-slate-900/20 overflow-y-auto p-4 custom-scrollbar">
          <div className="text-[10px] font-black text-slate-600 uppercase tracking-widest mb-4 px-2">Atom Hierarchy</div>
          <div className="space-y-1">
            {atoms.map(a => (
              <button
                key={a.id}
                onClick={() => setSelectedAtomId(a.id)}
                className={`w-full text-left px-3 py-2 rounded-lg text-xs font-bold transition-all ${
                  selectedAtomId === a.id 
                    ? 'bg-slate-800 text-blue-400 border border-slate-700' 
                    : 'text-slate-500 hover:text-slate-300'
                }`}
              >
                {a.id}
              </button>
            ))}
          </div>
        </div>

        {/* Content Preview */}
        <div className="flex-1 overflow-y-auto p-12 custom-scrollbar bg-white">
          <div className="max-w-3xl mx-auto">
             <div className="bg-slate-100 p-4 rounded-lg mb-8 border border-slate-200">
               <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2 block">Markdown Frontmatter</span>
               <pre className="text-[10px] text-slate-600 mono whitespace-pre-wrap">
                 {atom ? generateMarkdown(atom).split('#')[0] : ''}
               </pre>
             </div>

             {atom ? (
               <article className="prose prose-slate prose-blue lg:prose-lg max-w-none">
                 <h1 className="text-slate-900 font-black tracking-tight">{atom.id}: {atom.name}</h1>
                 
                 <div className="flex items-center gap-4 py-6 border-y border-slate-100 my-8">
                   <span className="text-xs font-black uppercase tracking-widest px-3 py-1 bg-blue-50 text-blue-600 rounded-full border border-blue-100">
                     {atom.type}
                   </span>
                   <span className="text-xs font-black uppercase tracking-widest px-3 py-1 bg-slate-50 text-slate-500 rounded-full border border-slate-200">
                     v{atom.version}
                   </span>
                   <span className="text-xs text-slate-400 font-medium ml-auto">
                     {atom.owner} • {atom.team}
                   </span>
                 </div>

                 <h2 className="text-slate-800">Description</h2>
                 <p className="text-slate-600">{atom.content.summary}</p>

                 {atom.content.steps && (
                   <>
                     <h2 className="text-slate-800">Standard Operating Procedure</h2>
                     <ol className="text-slate-600">
                       {atom.content.steps.map((step, i) => (
                         <li key={i}>{step}</li>
                       ))}
                     </ol>
                   </>
                 )}

                 {atom.content.exceptions && (
                   <>
                     <h2 className="text-slate-800">Business Exceptions</h2>
                     <table className="min-w-full">
                       <thead>
                         <tr>
                           <th className="text-left text-xs uppercase tracking-widest text-slate-400 py-3">Condition</th>
                           <th className="text-left text-xs uppercase tracking-widest text-slate-400 py-3">Resolution Action</th>
                         </tr>
                       </thead>
                       <tbody className="divide-y divide-slate-100">
                         {atom.content.exceptions.map((exc, i) => (
                           <tr key={i}>
                             <td className="py-4 text-sm font-bold text-slate-700">{exc.condition}</td>
                             <td className="py-4 text-sm text-slate-600">{exc.action}</td>
                           </tr>
                         ))}
                       </tbody>
                     </table>
                   </>
                 )}

                 <h2 className="text-slate-800">Semantic Graph Relationships</h2>
                 <div className="grid grid-cols-1 gap-4">
                   {atom.edges.map((edge, i) => (
                     <div key={i} className="flex items-center gap-4 p-4 bg-slate-50 rounded-xl border border-slate-100">
                       <span className="text-[10px] font-black uppercase tracking-widest px-2 py-1 bg-white border border-slate-200 text-slate-500 rounded shadow-sm">
                         {edge.type}
                       </span>
                       <span className="text-sm font-bold text-blue-600 hover:underline cursor-pointer">
                         {edge.targetId}
                       </span>
                       <span className="text-xs text-slate-400 italic flex-1 truncate">
                         {edge.description || 'Global dependency reference.'}
                       </span>
                     </div>
                   ))}
                 </div>

                 <footer className="mt-20 pt-8 border-t border-slate-100 text-[10px] text-slate-400 uppercase tracking-widest font-black flex justify-between">
                   <span>Platform: GNDP v1.0</span>
                   <span>© 2024 Enterprise Knowledge Services</span>
                 </footer>
               </article>
             ) : (
               <div className="h-full flex items-center justify-center text-slate-300">
                 Select an atom to preview documentation
               </div>
             )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Publisher;
