#!/usr/bin/env python3
"""Post a PR comment using GITHUB_TOKEN based on a claude report file.
This script reads the JSON file produced by `scripts/claude_helper.py` and
posts a comment to the PR with a short summary.
"""
import argparse
import os
import sys
import json
import requests

GITHUB_API = "https://api.github.com"


def post_comment(repo, pr_number, body, token):
    url = f"{GITHUB_API}/repos/{repo}/issues/{pr_number}/comments"
    resp = requests.post(url, headers={"Authorization": f"token {token}"}, json={"body": body})
    resp.raise_for_status()
    return resp.json()


def read_claude(path):
    if not os.path.exists(path):
        return None
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)


def build_comment(report):
    if not report:
        return "GNDP Agent: no report available."
    out = report.get("model_output", {})
    summary = out.get("summary", "No summary")
    risk = out.get("risk_level", "UNKNOWN")
    modules = out.get("affected_modules", [])
    reviewers = out.get("suggested_reviewers", [])

    lines = ["### GNDP Impact Summary", "", f"**Risk level:** {risk}", "", f"**Summary:** {summary}", ""]
    if modules:
        lines.append("**Affected modules:** " + ", ".join(modules))
    if reviewers:
        lines.append("**Suggested reviewers:** " + ", ".join(reviewers))

    lines.append("\n*This comment was generated by the GNDP Agent.*")
    return "\n".join(lines)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--pr", required=True)
    p.add_argument("--claude", required=True)
    args = p.parse_args()

    repo = os.environ.get("GITHUB_REPOSITORY")
    token = os.environ.get("GITHUB_TOKEN")
    if not repo or not token:
        print("Missing GITHUB_REPOSITORY or GITHUB_TOKEN environment variables", file=sys.stderr)
        sys.exit(1)

    report = read_claude(args.claude)
    body = build_comment(report)
    try:
        post_comment(repo, args.pr, body, token)
        print("Posted PR comment")
    except Exception as e:
        print("Failed to post PR comment:", e, file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
